### ISSUE TITLE
Iniciar debate sobre el diseño del sistema

### ISSUE THREAD

**Issue by mdelapenya** [gdgtoledo/linneo#1]
Discutamos aquí sobre:
- APIs
- Lenguaje
- Entidades del dominio
- Tipos de tests
- Casos de uso
- etc.

**Comment by mdelapenya** [comment]
## Entidades del Dominio
Un primer posible enfoque podría ser éste, en el que se tiene una única entidad `Tree`:
```yml
tree:
  name: string
  geo:
    lat: float
    long: float
```
El `name` por defecto sería a `almez`, porque si lo dejamos así sería extensible a cualquier otro tipo de árbol.
En cuanto a la geolocalización, con almacenar las coordenadas sería suficiente para abstraerlo del sistema de representación (Google Maps, Open Street Map...)

**Comment by mdelapenya** [comment]
## Casos de Uso
- Como ciudadano, quiero ver todos los árboles del tipo `almez` en un mapa
- Como administrador, quiero dar de alta un árbol del tipo `almez` a partir de su ubicación
- Como administrador, quiero dar de baja un árbol del tipo `almez` a partir de su ubicación

**Comment by javierlopezdeancos** [comment]
Segun lo que veo, estaria bien 

```yml
tree:
  id: int
  type: string
  geo:
    lat: float
    long: float
```

**Comment by javierlopezdeancos** [comment]
El caso de uso

Caso de uso de Usuario
1 se puede resolver en una UI de mapas

Caso de uso de Administrador
2 y 3 se puede resolver en un cli

**Comment by javierlopezdeancos** [comment]
EL lenguaje prefiero ver en qué deriba esto para ver la mejor opción en cuanto al lenguaje

**Comment by mdelapenya** [comment]
Lo del filtrado por barrio lo veo como una evolución de la primera iteración, verlos en un mapa, el tema del barrio es un concepto que posiblemente los mapas open no tengan per-sé

**Comment by felixortegam** [comment]
```
tree:
  id: int
  type: string
  geoposition:
    latitude: float
    longitude: float
```
Mientras no nos cobren por letra :)
