### ISSUE TITLE
Entidades del Dominio

### ISSUE THREAD

**Issue by javierlopezdeancos** [gdgtoledo/linneo#2]
## Entidades del Dominio
Un primer posible enfoque podría ser éste, en el que se tiene una única entidad `Tree`:
```yml
tree:
  name: string
  geo:
    lat: float
    long: float
```
El `name` por defecto sería a `almez`, porque si lo dejamos así sería extensible a cualquier otro tipo de árbol.
En cuanto a la geolocalización, con almacenar las coordenadas sería suficiente para abstraerlo del sistema de representación (Google Maps, Open Street Map...)

_Originally posted by @mdelapenya in https://github.com/gdgtoledo/almeces-de-toledo/issues/1#issuecomment-519151848_

Umm según lo que comentas debajo, estaría bien colocar un type: String em eñ struc

**Comment by mdelapenya** [comment]
```
tree:
  id: int
  type: string
  geoposition:
    latitude: float
    longitude: float
```
Mientras no nos cobren por letra :)

_Originally posted by @felixortegam in https://github.com/gdgtoledo/linneo/issues/1#issuecomment-519190208_

**Comment by mdelapenya** [comment]
Entidades de dominio:

En lugar de Tree, veo mejor Plant.

Incluiría el género y especie según la clasificación de Linneo, ya que es una de las clasificaciones de plantas más aceptadas y extendidas

```yml
plant:
  id: int
  genere: string
  species: string
  geo:
    lat: float
    long: float
```

_Originally posted by @manudevelopia in https://github.com/gdgtoledo/linneo/issues/1#issuecomment-519190679_
